#!/usr/bin/env bash

git clone https://github.com/chriskempson/base16-shell.git "$HOME/.config/base16-shell"
ln -s "$HOME/.config/base16-shell/scripts/base16-tomorrow-night.sh" "$HOME/.base16_theme"

